### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by VoicuTomut**
These are from the beginning of my journey in Quantum computing . They are all taken from Qiskit textbook so I don't know if they're fit here .

### CODE REVIEW

**Comment by aditya-giri** [comment]
Thanks for the PR @VoicuTomut! 😄 

Couple of things - 
1. I see your IBMQ token in some of the notebooks. You might want to remove this because it's private. Instead you can add a comment asking users to fill their token in.
2. There's already a notebook for teleportation so you can remove that. And for the rest of the notebooks it would be good to follow the lowercase hyphen-separated naming convention (like quantum-teleportation.ipynb)
3. Could you maybe add a few explanations about what the circuit does etc? I've been meaning to add them for the other 2 as well but I haven't had the time 😅 - but no worries, if it's too much work you can skip this.

**Review by aditya-giri — CHANGES_REQUESTED** [review]
Thanks for the PR @VoicuTomut! 😄

Couple of things -

I see your IBMQ token in some of the notebooks. You might want to remove this because it's private. Instead you can add a comment asking users to fill their token in.
There's already a notebook for teleportation so you can remove that. And for the rest of the notebooks it would be good to follow the lowercase hyphen-separated naming convention (like quantum-teleportation.ipynb)
Could you maybe add a few explanations about what the circuit does etc? I've been meaning to add them for the other 2 as well but I haven't had the time 😅 - but no worries, if it's too much work you can skip this.

**Comment by VoicuTomut** [comment]
Thanks for telling me about the token. I renamed the files but unfortunately I didn't have time to add more comments.

**Comment by aditya-giri** [comment]
Looks good, we can merge this and then start structuring the code better as the repo takes shape 👍

**Review by aditya-giri — APPROVED** [review]

**Pull request merged**
